# author: Radoslav Grencik <xgrenc00@stud.fit.vutbr.cz>

################################################################################

run:
	python3 OWclient.py ${api_key} ${city}

pack:
	rm -rf xgrenc00.zip
	zip xgrenc00.zip *
